version: '3.7'

services:
  talk-archiver:
    build:
      context: .
    volumes:
      - node_modules:/app/node_modules
      - ./:/app
    ports:
      - "8080:8080"
    environment:
      - "NODE_RAM=8192" # https://nodejs.org/api/cli.html#cli_max_old_space_size_size_in_mbytes
      - "AWS_DEFAULT_REGION=${AWS_REGION:-us-east-1}"
      - "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
      - "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"

volumes:
  node_modules: